source 'http://rubygems.org'

gem 'rails', '3.2.2'

gem 'pg', '~> 0.13.2'
gem 'foreigner', '~> 1.1.5'

gem 'devise', '~> 2.0.4'
gem 'omniauth', '~> 1.0.3'
gem 'omniauth-twitter', '~> 0.0.8'
gem 'omniauth-facebook', '~> 1.2.0'
gem 'omniauth-openid',' ~> 1.0.1'
gem 'cancan', '~> 1.6.7'

gem 'has_scope', '~> 0.5.1'
gem 'inherited_resources', '~> 1.3.1'
gem 'will_paginate', '~> 3.0.3'

gem 'haml-rails', '~> 0.3.4'
gem 'formtastic', '~> 2.1.1'
gem 'ckeditor', '~> 3.7.0.rc3', :git => 'git://github.com/chipiga/ckeditor.git'
# gem 'themes_for_rails', '~> 1.0.0rc1'
gem 'meta-tags', '~> 1.2.5', :require => 'meta_tags'
gem 'truncate_html', '~> 0.5.4'
gem 'htmlentities', '~> 4.3.1'

gem 'thinking-sphinx', '2.0.11', :require => 'thinking_sphinx'
gem 'paperclip', '~> 3.0.0', :git => 'git://github.com/thoughtbot/paperclip.git'
gem 'ancestry', '~> 1.2.5'
gem 'paper_trail', '~> 2.6.3' # should be included before attribute_normalizer
gem 'attribute_normalizer', '~> 1.1.0'
gem 'validates_lengths_from_database', '~> 0.1.3'
gem 'acts-as-taggable-on', '~> 2.2.2'
gem 'friendly_id', '~> 3.3.2.0' # upgrade to 4.0.0 ?
gem 'clean-bitmask-attribute', '~> 2.0.3', :require => 'bitmask-attribute'

gem 'refraction', '~> 0.2.0'
gem 'recaptcha', '~> 0.3.4', :require => "recaptcha/rails"
gem 'fastercsv', '~> 1.5.4'
gem 'delayed_job_active_record', '~> 0.3.2'
gem "backup", :git => "git://github.com/devmen/backup.git" # TODO upgrade? Resolve Platform conflict
gem 'whenever', :require => false

gem 'jquery_flash', :git => 'git://github.com/chipiga/jquery_flash.git' # TODO redo?
gem 'jquery-rails', '~> 2.0.1'

group :assets do
  gem 'sass-rails', '~> 3.2.5'
  gem 'coffee-rails', '~> 3.2.2'
  gem 'uglifier', '~> 1.2.4'
  gem 'compass-rails', '~> 1.0.1'
  gem 'therubyracer', '~> 0.10.0'
  # gem 'mustang', '~> 0.2.1'
  # gem 'johnson', '~> 2.0.0.pre3'
end

group :production do
  gem 'passenger', '3.0.11'
  gem 'exception_notification', '~> 2.5.2'
  gem 'newrelic_rpm', '~> 3.3.2' # should be included before DJ ?
  gem 'daemons', '~> 1.1.8'
end

group :development do
  # gem 'rails-dev-tweaks'
  gem 'mailcatcher' # 'letter_opener'
  # gem 'ruby-debug', :platforms => :mri_18
  # gem 'ruby-debug19', :require => 'ruby-debug', :platforms => :mri_19
  gem 'looksee'
  gem 'awesome_print'
  gem 'wirble'
  gem 'capistrano'
  # gem "rails3-footnotes", :git => 'http://github.com/indirect/rails-footnotes.git' # this shit is very buggy don't forget to switch it off back
  # gem 'silent-postgres'
end

group :test do
  gem 'rspec-rails',        '~> 2.9.0'
  gem 'factory_girl_rails', '~> 3.0.0'
  gem 'webrat',             '~> 0.7.3'
  gem 'rr',                 '~> 1.0.3'
  gem 'spork',              '~> 1.0.0rc2'
  gem 'guard-spork',        '~> 0.5.2'
  gem 'guard-rspec',        '~> 0.7.0'
  gem 'guard-bundler',      '~> 0.1'
  gem 'rcov',               '~> 0.9.10'

  gem 'rb-fsevent', '>= 0.4.3', :require => false
  gem 'growl',      '~> 1.0.3', :require => false

  gem 'rb-inotify', '>= 0.8.6', :require => false
  gem 'libnotify',  '~> 0.5.7', :require => false
end
