source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem "bundler", "~> 1.2.0"
gem "rake", "~> 0.9.2.2"

# Database
gem "pg", "~> 0.14.0"

# Auth
gem "devise", ">= 2.1.2"


# Models
gem "paperclip", "~> 3.1.4"

# Controllers

# JS
gem "jquery-rails", "~> 2.1.1"

# Views
gem "haml", ">= 3.1.7"
gem "simple_form", "~> 2.0.2"

# Assets
gem "therubyracer", "~> 0.10.2", :group => :assets, :platform => :ruby
gem "bootstrap-sass", ">= 2.0.4.0"
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

# Misc
gem "unicorn",     "~> 4.3.1"
gem "cocaine", "~> 0.3.0"


group :development do
  gem "haml-rails", ">= 0.3.4"
  gem "hpricot", ">= 0.8.6"
  gem "ruby_parser", ">= 2.3.1"
  gem 'capistrano-unicorn', '~> 0.1.6'
  gem "capistrano", "~> 2.12.0", :require => false
  gem "capistrano-ext"
  gem "capistrano_colors", "~> 0.5.5", :require => false
  gem 'rvm'
  gem 'rvm-capistrano', "~> 1.2.3"
  gem "quiet_assets", "~> 1.0.1"

end

group :development, :test do
  gem "rspec-rails", ">= 2.11.0"
  gem "factory_girl_rails", ">= 4.0.0"
end

group :test do
  gem "capybara", ">= 1.1.2"
  gem "email_spec", ">= 1.2.1"
  gem 'shoulda', '>= 3.1.0'
  gem "timecop", "~> 0.3.5"
  gem "database_cleaner", ">= 0.8.0"
  gem "launchy", ">= 2.1.0"
  gem "json_spec", "~> 1.0.3"
  gem "webmock", "~> 1.8.6"
  gem "rack-test", "~> 0.6.1"
  gem "ffaker", "~> 1.12.1"

end
